import { Info } from "lucide-react";

export function ResponsibleAIDisclaimer() {
  return (
    <div className="mb-6 flex items-start gap-3 rounded-lg border border-border bg-accent/40 px-4 py-3 text-sm text-foreground/80">
      <Info className="mt-0.5 h-4 w-4 shrink-0 text-primary" />
      <p>
        <span className="font-medium text-foreground">Responsible AI:</span>{" "}
        AI-generated content may be inaccurate or incomplete. Review and verify before
        sending, acting, or sharing.
      </p>
    </div>
  );
}

export function DisclaimerFootnote() {
  return (
    <p className="mt-3 text-xs text-muted-foreground">
      Generated by AI — please review for accuracy before use.
    </p>
  );
}
